In [1]:
import sys  
sys.path.insert(0, '/Users/ariannataormina/Documents/GitHub/DataAnalysisExample/code')

In [2]:
#from initialization import *
from __init__ import *
#time.sleep(5)

Import succesfull
Tokens and default var imported
Functions imported

# Token to hide

In [3]:
RAPIDAPI_KEY="ab02b45763mshb0174d666dd1fc9p131682jsn2e6413a69cd1"
RAPIDAPI_HOST="mashvisor-api.p.rapidapi.com"
headers = {
      'x-rapidapi-key': RAPIDAPI_KEY,
      'x-rapidapi-host': RAPIDAPI_HOST,
      }
print (headers)

{'x-rapidapi-key': 'ab02b45763mshb0174d666dd1fc9p131682jsn2e6413a69cd1', 'x-rapidapi-host': 'mashvisor-api.p.rapidapi.com'}

In [4]:
foliumToken="pk.eyJ1IjoiYXJpdGFvODkiLCJhIjoiY2tsZ3pmZTV0MWg5MjJwcDczZHV1anQ5cCJ9.aPiO2IJde1Ipk_NGTtehLw"

In [15]:
SocrataAPIKeyID="5a93m0xbwos9mncihhcbeect2"
SocrataAPIKeySecret="3pzvqyr3091p6h03wn6e9eca6xfvz9fnp9me98hkr613tdxki4"
SocrataToken="V9LzPUYxEdHVctEnhELErrA3M"
SocrataSecretToken="UhKSW8y3HnpXvRjjqL6iipb2yux1oJq0_6Iv"

# Set variables

In [6]:
state,city = "CA", "San Francisco"

# Query Airbnb

In [ ]:
# test
# all_listings = get_listings(state,city, headers,page = 1, items = 10)

per page only 20 results, so repeat query over 57 pages now

In [ ]:
"""
SFlistings = []
numpages = 58
for i in tqdm(range(1,numpages)):
    #print(i)
    page_listings = get_listings(state,city, headers,page = i, items = 20)
    if isinstance(page_listings,list) and len(page_listings)>0:
        SFlistings.extend(page_listings)
    else: 
        print ("page {i} no results")
    time.sleep(1)
   """

In [ ]:
#type(SFlistings), len(SFlistings)

In [ ]:
#df = pd.DataFrame(SFlistings)
#df

In [ ]:
#storing 
#df.to_pickle("../data/df_SFlistings.pkl")

In [ ]:
df.reviews.unique()

# Query Socrata

data is available in nice .csv format and it is also quearable from the SOCA API.

- peak on the size of the data with csv
- query for the right size with the API:)

In [26]:
data_20032018 = pd.read_csv("../data/Police_Department_Incident_Reports__Historical_2003_to_May_2018.csv")

In [39]:
data_20032018

,PdId,IncidntNum,Incident Code,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,...,Fix It Zones as of 2017-11-06 2 2,DELETE - HSOC Zones 2 2,Fix It Zones as of 2018-02-07 2 2,"CBD, BID and GBD Boundaries as of 2017 2 2","Areas of Vulnerability, 2016 2 2",Central Market/Tenderloin Boundary 2 2,Central Market/Tenderloin Boundary Polygon - Updated 2 2,HSOC Zones as of 2018-06-05 2 2,OWED Public Spaces 2 2,Neighborhoods 2
0,3114751606302,31147516,6302,LARCENY/THEFT,PETTY THEFT FROM A BUILDING,Sunday,09/28/2003,10:00,SOUTHERN,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5069701104134,50697011,4134,ASSAULT,BATTERY,Wednesday,06/22/2005,12:20,NORTHERN,NONE,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,97.0
2,6074729204104,60747292,4104,ASSAULT,ASSAULT,Saturday,07/15/2006,00:55,CENTRAL,NONE,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,106.0
3,7103536315201,71035363,15201,ASSAULT,STALKING,Tuesday,09/25/2007,00:01,TARAVAL,NONE,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,49.0
4,11082415274000,110824152,74000,MISSING PERSON,MISSING ADULT,Saturday,09/24/2011,11:00,TARAVAL,LOCATED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2129520,16099543005043,160995430,5043,BURGLARY,"BURGLARY OF RESIDENCE, UNLAWFUL ENTRY",Thursday,12/01/2016,17:30,NORTHERN,NONE,...,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,21.0
2129521,16093783009031,160937830,9031,OTHER OFFENSES,"MONEY, PROPERTY OR LABOR, FRAUDULENTLY OBTAINING",Monday,11/14/2016,00:01,INGLESIDE,NONE,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,58.0
2129522,17078486916110,170784869,16110,DRUG/NARCOTIC,POSSESSION OF HEROIN FOR SALES,Tuesday,09/26/2017,01:38,CENTRAL,"ARREST, BOOKED",...,23.0,NaN,23.0,1.0,2.0,NaN,NaN,NaN,NaN,106.0
2129523,18014823304138,180148233,4138,ASSAULT,"BATTERY, FORMER SPOUSE OR DATING RELATIONSHIP",Saturday,02/24/2018,20:30,CENTRAL,"ARREST, BOOKED",...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,108.0
2129524,16044156851040,160441568,51040,NON-CRIMINAL,AIDED CASE,Monday,05/30/2016,11:33,SOUTHERN,NONE,...,NaN,1.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,21.0

In [27]:
data_20182021 = pd.read_csv("../data/Police_Department_Incident_Reports__2018_to_Present.csv")

In [48]:
data_20182021.tail()

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,SF Find Neighborhoods,Current Police Districts,Current Supervisor Districts,Analysis Neighborhoods,HSOC Zones as of 2018-06-05,OWED Public Spaces,Central Market/Tenderloin Boundary Polygon - Updated,Parks Alliance CPSI (27+TL sites),ESNCAG - Boundary File,"Areas of Vulnerability, 2016"
443924,2021/03/30 04:55:00 AM,2021/03/30,04:55,2021,Tuesday,2021/03/30 05:00:00 AM,101735627130,1017356,210196906,210890312.0,...,50.0,4.0,3.0,21.0,NaN,NaN,NaN,NaN,NaN,2.0
443925,2020/03/12 04:47:00 PM,2020/03/12,16:47,2020,Thursday,2020/03/12 04:47:00 PM,101747803071,1017478,200183935,NaN,...,11.0,8.0,6.0,31.0,NaN,NaN,NaN,NaN,NaN,1.0
443926,2021/03/18 06:40:00 PM,2021/03/18,18:40,2021,Thursday,2021/03/30 09:51:00 AM,101748306374,1017483,210197998,210890963.0,...,21.0,5.0,10.0,36.0,1.0,35.0,1.0,NaN,NaN,2.0
443927,2020/02/23 02:14:00 PM,2020/02/23,14:14,2020,Sunday,2020/02/23 02:23:00 PM,101749503071,1017495,200136796,NaN,...,32.0,1.0,10.0,34.0,NaN,NaN,NaN,NaN,NaN,2.0
443928,2021/03/30 05:00:00 AM,2021/03/30,05:00,2021,Tuesday,2021/03/30 05:30:00 AM,101737075025,1017370,200624644,210890452.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
len(data_20032018), len(data_20182021)

(2129525, 443929)

In [31]:
print (*list(data_20032018.columns), sep = "\n")

PdId
IncidntNum
Incident Code
Category
Descript
DayOfWeek
Date
Time
PdDistrict
Resolution
Address
X
Y
location
SF Find Neighborhoods 2 2
Current Police Districts 2 2
Current Supervisor Districts 2 2
Analysis Neighborhoods 2 2
DELETE - Fire Prevention Districts 2 2
DELETE - Police Districts 2 2
DELETE - Supervisor Districts 2 2
DELETE - Zip Codes 2 2
DELETE - Neighborhoods 2 2
DELETE - 2017 Fix It Zones 2 2
Civic Center Harm Reduction Project Boundary 2 2
Fix It Zones as of 2017-11-06  2 2
DELETE - HSOC Zones 2 2
Fix It Zones as of 2018-02-07 2 2
CBD, BID and GBD Boundaries as of 2017 2 2
Areas of Vulnerability, 2016 2 2
Central Market/Tenderloin Boundary 2 2
Central Market/Tenderloin Boundary Polygon - Updated 2 2
HSOC Zones as of 2018-06-05 2 2
OWED Public Spaces 2 2
Neighborhoods 2

In [32]:
print (*list(data_20182021.columns), sep = "\n")

Incident Datetime
Incident Date
Incident Time
Incident Year
Incident Day of Week
Report Datetime
Row ID
Incident ID
Incident Number
CAD Number
Report Type Code
Report Type Description
Filed Online
Incident Code
Incident Category
Incident Subcategory
Incident Description
Resolution
Intersection
CNN
Police District
Analysis Neighborhood
Supervisor District
Latitude
Longitude
point
SF Find Neighborhoods
Current Police Districts
Current Supervisor Districts
Analysis Neighborhoods
HSOC Zones as of 2018-06-05
OWED Public Spaces
Central Market/Tenderloin Boundary Polygon - Updated
Parks Alliance CPSI (27+TL sites)
ESNCAG - Boundary File
Areas of Vulnerability, 2016

In [16]:
client = Socrata("data.sfgov.org",
                SocrataToken,
                username="ariannataormina89@gmail.com",
                password="Gattalulu1!")

### Get Data 2013-2018

In [33]:
#results_20132018 = client.get("tmnf-yvry", limit=2129525)

In [4]:
#df_results_20132018 = pd.DataFrame.from_records(results_20132018)

In [23]:
#loading 
df_results_20032018 =  pd.read_pickle("../data/df_results_20032018_raw.pkl")

In [24]:
df_results_20032018.columns

Index(['pdid', 'incidntnum', 'incident_code', 'category', 'descript',
       'dayofweek', 'date', 'time', 'pddistrict', 'resolution', 'address', 'x',
       'y'],
      dtype='object')

In [25]:
df_results_20032018 = addTime(df_results_20032018, 'time')
df_results_20032018 = addDate(df_results_20032018, 'date')
#df_results_20032018 = df_results_20032018[df_results_20032018.columns[:-1]]
df_results_20032018

/Users/ariannataormina/Documents/GitHub/DataAnalysisExample/code/functions_df.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourOfDay'] = df['Time'].dt.hour

,Date,hourOfDay,minuteOfDay,pdid,incidntnum,incident_code,category,descript,dayofweek,date,time,pddistrict,resolution,address,x,y,Time
0,2003-09-28,10,0,3114751606302,031147516,06302,LARCENY/THEFT,PETTY THEFT FROM A BUILDING,Sunday,2003-09-28T00:00:00.000,10:00,SOUTHERN,NONE,1ST ST / BRANNAN ST,-120.5,90,2021-04-01 10:00:00
1,2005-06-22,12,20,5069701104134,050697011,04134,ASSAULT,BATTERY,Wednesday,2005-06-22T00:00:00.000,12:20,NORTHERN,NONE,1200 Block of EDDY ST,-122.428223303176,37.7818959488603,2021-04-01 12:20:00
2,2006-07-15,0,55,6074729204104,060747292,04104,ASSAULT,ASSAULT,Saturday,2006-07-15T00:00:00.000,00:55,CENTRAL,NONE,1600 Block of POWELL ST,-122.410672425337,37.799788690123,2021-04-01 00:55:00
3,2007-09-25,0,1,7103536315201,071035363,15201,ASSAULT,STALKING,Tuesday,2007-09-25T00:00:00.000,00:01,TARAVAL,NONE,400 Block of ULLOA ST,-122.458226300605,37.7413616001449,2021-04-01 00:01:00
4,2011-09-24,11,0,11082415274000,110824152,74000,MISSING PERSON,MISSING ADULT,Saturday,2011-09-24T00:00:00.000,11:00,TARAVAL,LOCATED,3200 Block of SAN JOSE AV,-122.459172646607,37.7082001648459,2021-04-01 11:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2129520,2016-12-01,17,30,16099543005043,160995430,05043,BURGLARY,"BURGLARY OF RESIDENCE, UNLAWFUL ENTRY",Thursday,2016-12-01T00:00:00.000,17:30,NORTHERN,NONE,300 Block of FULTON ST,-122.42253647830613,37.7787958771466,2021-04-01 17:30:00
2129521,2016-11-14,0,1,16093783009031,160937830,09031,OTHER OFFENSES,"MONEY, PROPERTY OR LABOR, FRAUDULENTLY OBTAINING",Monday,2016-11-14T00:00:00.000,00:01,INGLESIDE,NONE,0 Block of CONCORD ST,-122.44276988992716,37.71275870748528,2021-04-01 00:01:00
2129522,2017-09-26,1,38,17078486916110,170784869,16110,DRUG/NARCOTIC,POSSESSION OF HEROIN FOR SALES,Tuesday,2017-09-26T00:00:00.000,01:38,CENTRAL,"ARREST, BOOKED",500 Block of BROADWAY ST,-122.40586321263237,37.79802284521844,2021-04-01 01:38:00
2129523,2018-02-24,20,30,18014823304138,180148233,04138,ASSAULT,"BATTERY, FORMER SPOUSE OR DATING RELATIONSHIP",Saturday,2018-02-24T00:00:00.000,20:30,CENTRAL,"ARREST, BOOKED",500 Block of CALIFORNIA ST,-122.40330497576683,37.792727599465884,2021-04-01 20:30:00
2129524,2016-05-30,11,33,16044156851040,160441568,51040,NON-CRIMINAL,AIDED CASE,Monday,2016-05-30T00:00:00.000,11:33,SOUTHERN,NONE,1600 Block of MARKET ST,-122.4209584484125,37.773955543024975,2021-04-01 11:33:00

In [26]:
df_results_20032018.sort_values(by=['Date',"hourOfDay","minuteOfDay"], inplace=True, ascending=True)

In [27]:
df_results_20032018.reset_index(inplace=True,drop=True)
df_results_20032018

,Date,hourOfDay,minuteOfDay,pdid,incidntnum,incident_code,category,descript,dayofweek,date,time,pddistrict,resolution,address,x,y,Time
0,2003-01-01,0,1,3032234164070,030322341,64070,SUSPICIOUS OCC,SUSPICIOUS OCCURRENCE,Wednesday,2003-01-01T00:00:00.000,00:01,TARAVAL,UNFOUNDED,1700 Block of 21ST AV,-122.478747875056,37.7550587958463,2021-04-01 00:01:00
1,2003-01-01,0,1,5136240909020,051362409,09020,FORGERY/COUNTERFEITING,"CHECKS, MAKE OR PASS FICTITIOUS",Wednesday,2003-01-01T00:00:00.000,00:01,INGLESIDE,NOT PROSECUTED,5500 Block of MISSION ST,-122.445418223794,37.7120747965978,2021-04-01 00:01:00
2,2003-01-01,0,1,5075339009340,050753390,09340,FRAUD,FRAUDULENT CREDIT APPLICATION,Wednesday,2003-01-01T00:00:00.000,00:01,BAYVIEW,NONE,0 Block of OSCEOLA LN,-122.383085144615,37.7317523387371,2021-04-01 00:01:00
3,2003-01-01,0,1,4141636719050,041416367,19050,OTHER OFFENSES,OBSCENE PHONE CALLS(S),Wednesday,2003-01-01T00:00:00.000,00:01,BAYVIEW,NONE,500 Block of HOLYOKE ST,-122.40772139488,37.7245472609848,2021-04-01 00:01:00
4,2003-01-01,0,1,4023213810125,040232138,10125,FRAUD,"FALSE PRETENSES, GRAND THEFT",Wednesday,2003-01-01T00:00:00.000,00:01,SOUTHERN,NONE,800 Block of BRYANT ST,-122.403404791479,37.775420706711,2021-04-01 00:01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2129520,2018-05-15,2,1,18036087965010,180360879,65010,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Tuesday,2018-05-15T00:00:00.000,02:01,MISSION,"ARREST, BOOKED",CAPP ST / 21ST ST,-122.41781255878655,37.757100579642824,2021-04-01 02:01:00
2129521,2018-05-15,2,1,18036087926150,180360879,26150,OTHER OFFENSES,PAROLE VIOLATION,Tuesday,2018-05-15T00:00:00.000,02:01,MISSION,"ARREST, BOOKED",CAPP ST / 21ST ST,-122.41781255878655,37.757100579642824,2021-04-01 02:01:00
2129522,2018-05-15,2,1,18036087965015,180360879,65015,OTHER OFFENSES,TRAFFIC VIOLATION,Tuesday,2018-05-15T00:00:00.000,02:01,MISSION,"ARREST, BOOKED",CAPP ST / 21ST ST,-122.41781255878655,37.757100579642824,2021-04-01 02:01:00
2129523,2018-05-15,4,14,18036094864020,180360948,64020,NON-CRIMINAL,"AIDED CASE, MENTAL DISTURBED",Tuesday,2018-05-15T00:00:00.000,04:14,SOUTHERN,NONE,MARKET ST / SOUTH VAN NESS AV,-122.41925789481357,37.77514629165388,2021-04-01 04:14:00
2129524,2018-05-15,10,30,18036228907023,180362289,07023,VEHICLE THEFT,STOLEN MOTORCYCLE,Tuesday,2018-05-15T00:00:00.000,10:30,SOUTHERN,NONE,700 Block of TEHAMA ST,-122.41191202732877,37.77520656149669,2021-04-01 10:30:00

In [28]:
#storing 
df_results_20032018.to_pickle("../data/df_clean_results_20032018_raw.pkl")

In [35]:
#loading 
df_results_20032017 =  pd.read_pickle("../data/df_clean_results_20032018_raw.pkl")

In [39]:
def maskDfbyDate(df,start_date, end_date):
    mask = (df['Date'] >= start_date) & (df['Date'] < end_date)
    df_masked = df.loc[mask].sort_values(by=['Date',"hourOfDay","minuteOfDay"], inplace=False, ascending=True)
    return df_masked

In [40]:
start_date = "01/01/2013" # mm/dd/yyyy
end_date = "01/01/2018"

In [41]:
df_results_20032017 = maskDfbyDate(df_results_20032017,start_date, end_date)

In [42]:
df_results_20032017.tail(1)

,Date,hourOfDay,minuteOfDay,pdid,incidntnum,incident_code,category,descript,dayofweek,date,time,pddistrict,resolution,address,x,y,Time
2084465,2017-12-31,23,58,18000041704134,180000417,04134,ASSAULT,BATTERY,Sunday,2017-12-31T00:00:00.000,23:58,SOUTHERN,NONE,800 Block of BRYANT ST,-122.40340479147905,37.775420706711,2021-04-01 23:58:00

In [43]:
#storing 
df_results_20032017.to_pickle("../data/df_clean_results_20032017_raw.pkl")

### Get Data 2018 to now

In [17]:
results_20182020 = client.get("wg3w-h783", limit=443929)

In [18]:
##loading raw crime dataset 2018-2020
df_results_20182020 = pd.read_pickle("../data/df_results_20182020_raw.pkl")
df_results_20182020

,Date,incident_time,incident_year,incident_day_of_week,report_datetime,row_id,incident_id,incident_number,cad_number,report_type_code,...,incident_subcategory,incident_description,resolution,intersection,cnn,police_district,analysis_neighborhood,supervisor_district,latitude,longitude
0,2018-01-01,09:26,2018,Monday,2018-01-01T09:27:00.000,61893007041,618930,171052174,173641140,VS,...,Recovered Vehicle,"Vehicle, Recovered, Auto",Open or Active,03RD ST \ HOLLISTER AVE,20471000,Southern,Bayview Hunters Point,10,37.72171587946975,-122.39594382884452
7174,2018-01-01,19:45,2018,Monday,2018-01-01T19:45:00.000,61905616710,619056,180002322,180013579,II,...,Drug Violation,"Narcotics Paraphernalia, Possession of",Cite or Arrest Adult,BLYTHDALE AVE \ SANTOS ST,20423000,Ingleside,Visitacion Valley,10,37.71073194458116,-122.41877184294184
7175,2018-01-01,19:45,2018,Monday,2018-01-01T19:45:00.000,61905663010,619056,180002322,180013579,II,...,Other,"Warrant Arrest, Local SF Warrant",Cite or Arrest Adult,BLYTHDALE AVE \ SANTOS ST,20423000,Ingleside,Visitacion Valley,10,37.71073194458116,-122.41877184294184
7176,2018-01-01,19:09,2018,Monday,2018-01-01T19:10:00.000,61905704083,619057,180002253,180013459,II,...,Aggravated Assault,"Firearm, Discharging in Grossly Negligent Manner",Cite or Arrest Adult,WESTBROOK CT \ HUDSON AVE,20189000,Bayview,Bayview Hunters Point,10,37.73497690238017,-122.38313398537929
7177,2018-01-01,19:09,2018,Monday,2018-01-01T19:10:00.000,61905712080,619057,180002253,180013459,II,...,Weapons Offense,"Firearm, Possession By Prohibited Person",Cite or Arrest Adult,WESTBROOK CT \ HUDSON AVE,20189000,Bayview,Bayview Hunters Point,10,37.73497690238017,-122.38313398537929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414918,2020-12-31,18:30,2020,Thursday,2020-12-31T19:04:00.000,99196628150,991966,206178148,NaN,II,...,Vandalism,"Malicious Mischief, Vandalism to Property",Open or Active,HAIGHT ST \ COLE ST,26414000,Park,Haight Ashbury,5,37.769526043647296,-122.45071018189665
414917,2020-12-31,22:05,2020,Thursday,2020-12-31T22:13:00.000,99188819057,991888,200791099,203663195,II,...,Intimidation,Terrorist Threats,Cite or Arrest Adult,EDDY ST \ LEAVENWORTH ST,24935000,Tenderloin,Tenderloin,6,37.78372378203807,-122.41424157409635
422759,2020-12-31,00:00,2020,Thursday,2021-01-19T09:36:00.000,99804306244,998043,216006959,NaN,II,...,Larceny - From Vehicle,"Theft, From Locked Vehicle, >$950",Open or Active,VAN NESS AVE \ BROADWAY,26547000,Northern,Russian Hill,2,37.79573710834212,-122.42341305643612
414909,2020-12-31,15:00,2020,Thursday,2021-01-01T13:53:00.000,99205604170,992056,210001145,210011707,II,...,Simple Assault,False Imprisonment,Open or Active,ELLIS ST \ HYDE ST,25144000,Tenderloin,Tenderloin,6,37.784448840613585,-122.41607173623363
414482,2020-12-31,15:42,2020,Thursday,2020-12-31T15:46:00.000,99182068050,991820,200790364,203661981,II,...,Traffic Collision,Traffic Collision,Cite or Arrest Adult,SOUTH VAN NESS AVE \ CESAR CHAVEZ ST,33364000,Mission,Mission,9,37.748212149468735,-122.41586279405455

In [19]:
df_results_20182020 = addTime(df_results_20182020, 'incident_time',insertAt=1)
df_results_20182020

/Users/ariannataormina/Documents/GitHub/DataAnalysisExample/code/functions_df.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourOfDay'] = df['Time'].dt.hour

,Date,hourOfDay,minuteOfDay,incident_time,incident_year,incident_day_of_week,report_datetime,row_id,incident_id,incident_number,...,incident_description,resolution,intersection,cnn,police_district,analysis_neighborhood,supervisor_district,latitude,longitude,Time
0,2018-01-01,9,26,09:26,2018,Monday,2018-01-01T09:27:00.000,61893007041,618930,171052174,...,"Vehicle, Recovered, Auto",Open or Active,03RD ST \ HOLLISTER AVE,20471000,Southern,Bayview Hunters Point,10,37.72171587946975,-122.39594382884452,2021-04-01 09:26:00
7174,2018-01-01,19,45,19:45,2018,Monday,2018-01-01T19:45:00.000,61905616710,619056,180002322,...,"Narcotics Paraphernalia, Possession of",Cite or Arrest Adult,BLYTHDALE AVE \ SANTOS ST,20423000,Ingleside,Visitacion Valley,10,37.71073194458116,-122.41877184294184,2021-04-01 19:45:00
7175,2018-01-01,19,45,19:45,2018,Monday,2018-01-01T19:45:00.000,61905663010,619056,180002322,...,"Warrant Arrest, Local SF Warrant",Cite or Arrest Adult,BLYTHDALE AVE \ SANTOS ST,20423000,Ingleside,Visitacion Valley,10,37.71073194458116,-122.41877184294184,2021-04-01 19:45:00
7176,2018-01-01,19,9,19:09,2018,Monday,2018-01-01T19:10:00.000,61905704083,619057,180002253,...,"Firearm, Discharging in Grossly Negligent Manner",Cite or Arrest Adult,WESTBROOK CT \ HUDSON AVE,20189000,Bayview,Bayview Hunters Point,10,37.73497690238017,-122.38313398537929,2021-04-01 19:09:00
7177,2018-01-01,19,9,19:09,2018,Monday,2018-01-01T19:10:00.000,61905712080,619057,180002253,...,"Firearm, Possession By Prohibited Person",Cite or Arrest Adult,WESTBROOK CT \ HUDSON AVE,20189000,Bayview,Bayview Hunters Point,10,37.73497690238017,-122.38313398537929,2021-04-01 19:09:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414918,2020-12-31,18,30,18:30,2020,Thursday,2020-12-31T19:04:00.000,99196628150,991966,206178148,...,"Malicious Mischief, Vandalism to Property",Open or Active,HAIGHT ST \ COLE ST,26414000,Park,Haight Ashbury,5,37.769526043647296,-122.45071018189665,2021-04-01 18:30:00
414917,2020-12-31,22,5,22:05,2020,Thursday,2020-12-31T22:13:00.000,99188819057,991888,200791099,...,Terrorist Threats,Cite or Arrest Adult,EDDY ST \ LEAVENWORTH ST,24935000,Tenderloin,Tenderloin,6,37.78372378203807,-122.41424157409635,2021-04-01 22:05:00
422759,2020-12-31,0,0,00:00,2020,Thursday,2021-01-19T09:36:00.000,99804306244,998043,216006959,...,"Theft, From Locked Vehicle, >$950",Open or Active,VAN NESS AVE \ BROADWAY,26547000,Northern,Russian Hill,2,37.79573710834212,-122.42341305643612,2021-04-01 00:00:00
414909,2020-12-31,15,0,15:00,2020,Thursday,2021-01-01T13:53:00.000,99205604170,992056,210001145,...,False Imprisonment,Open or Active,ELLIS ST \ HYDE ST,25144000,Tenderloin,Tenderloin,6,37.784448840613585,-122.41607173623363,2021-04-01 15:00:00
414482,2020-12-31,15,42,15:42,2020,Thursday,2020-12-31T15:46:00.000,99182068050,991820,200790364,...,Traffic Collision,Cite or Arrest Adult,SOUTH VAN NESS AVE \ CESAR CHAVEZ ST,33364000,Mission,Mission,9,37.748212149468735,-122.41586279405455,2021-04-01 15:42:00

In [21]:
df_results_20182020.columns

Index(['Date', 'hourOfDay', 'minuteOfDay', 'incident_time', 'incident_year',
       'incident_day_of_week', 'report_datetime', 'row_id', 'incident_id',
       'incident_number', 'cad_number', 'report_type_code',
       'report_type_description', 'incident_code', 'incident_category',
       'incident_subcategory', 'incident_description', 'resolution',
       'intersection', 'cnn', 'police_district', 'analysis_neighborhood',
       'supervisor_district', 'latitude', 'longitude', 'Time'],
      dtype='object')

In [9]:
# Convert to pandas DataFrame
#df_results_20182020 = pd.DataFrame.from_records(results_20182020)

# Make a boolean mask. start_date and end_date can be 
# datetime.datetimes, np.datetime64s, pd.Timestamps, or even datetime strings
#start_date = "01/01/2018"
#end_date = "01/01/2021"
#mask = (df_results_20182020['incident_date'] >= start_date) & (df_results_20182020['incident_date'] < end_date)

#df_results_20182020 = df_results_20182020.loc[mask].sort_values(by=['incident_date'], inplace=False, ascending=True)

,Date,hourOfDay,minuteOfDay,incident_year,incident_day_of_week,report_datetime,row_id,incident_id,incident_number,cad_number,...,incident_subcategory,incident_description,resolution,intersection,cnn,police_district,analysis_neighborhood,supervisor_district,latitude,longitude
0,2018-01-01,9,26,2018,Monday,2018-01-01T09:27:00.000,61893007041,618930,171052174,173641140,...,Recovered Vehicle,"Vehicle, Recovered, Auto",Open or Active,03RD ST \ HOLLISTER AVE,20471000,Southern,Bayview Hunters Point,10,37.72171587946975,-122.39594382884452
1,2018-01-01,19,45,2018,Monday,2018-01-01T19:45:00.000,61905616710,619056,180002322,180013579,...,Drug Violation,"Narcotics Paraphernalia, Possession of",Cite or Arrest Adult,BLYTHDALE AVE \ SANTOS ST,20423000,Ingleside,Visitacion Valley,10,37.71073194458116,-122.41877184294184
2,2018-01-01,19,45,2018,Monday,2018-01-01T19:45:00.000,61905663010,619056,180002322,180013579,...,Other,"Warrant Arrest, Local SF Warrant",Cite or Arrest Adult,BLYTHDALE AVE \ SANTOS ST,20423000,Ingleside,Visitacion Valley,10,37.71073194458116,-122.41877184294184
3,2018-01-01,19,9,2018,Monday,2018-01-01T19:10:00.000,61905704083,619057,180002253,180013459,...,Aggravated Assault,"Firearm, Discharging in Grossly Negligent Manner",Cite or Arrest Adult,WESTBROOK CT \ HUDSON AVE,20189000,Bayview,Bayview Hunters Point,10,37.73497690238017,-122.38313398537929
4,2018-01-01,19,9,2018,Monday,2018-01-01T19:10:00.000,61905712080,619057,180002253,180013459,...,Weapons Offense,"Firearm, Possession By Prohibited Person",Cite or Arrest Adult,WESTBROOK CT \ HUDSON AVE,20189000,Bayview,Bayview Hunters Point,10,37.73497690238017,-122.38313398537929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417109,2020-12-31,18,30,2020,Thursday,2020-12-31T19:04:00.000,99196628150,991966,206178148,NaN,...,Vandalism,"Malicious Mischief, Vandalism to Property",Open or Active,HAIGHT ST \ COLE ST,26414000,Park,Haight Ashbury,5,37.769526043647296,-122.45071018189665
417110,2020-12-31,22,5,2020,Thursday,2020-12-31T22:13:00.000,99188819057,991888,200791099,203663195,...,Intimidation,Terrorist Threats,Cite or Arrest Adult,EDDY ST \ LEAVENWORTH ST,24935000,Tenderloin,Tenderloin,6,37.78372378203807,-122.41424157409635
417111,2020-12-31,0,0,2020,Thursday,2021-01-19T09:36:00.000,99804306244,998043,216006959,NaN,...,Larceny - From Vehicle,"Theft, From Locked Vehicle, >$950",Open or Active,VAN NESS AVE \ BROADWAY,26547000,Northern,Russian Hill,2,37.79573710834212,-122.42341305643612
417112,2020-12-31,15,0,2020,Thursday,2021-01-01T13:53:00.000,99205604170,992056,210001145,210011707,...,Simple Assault,False Imprisonment,Open or Active,ELLIS ST \ HYDE ST,25144000,Tenderloin,Tenderloin,6,37.784448840613585,-122.41607173623363
417113,2020-12-31,15,42,2020,Thursday,2020-12-31T15:46:00.000,99182068050,991820,200790364,203661981,...,Traffic Collision,Traffic Collision,Cite or Arrest Adult,SOUTH VAN NESS AVE \ CESAR CHAVEZ ST,33364000,Mission,Mission,9,37.748212149468735,-122.41586279405455

In [30]:
df_results_20182020.sort_values(by=['Date',"hourOfDay","minuteOfDay"], inplace=True, ascending=True)

In [33]:
#df_results_20182020.reset_index(inplace=True,drop=True)
df_results_20182020 = df_results_20182020[['Date','hourOfDay','minuteOfDay','incident_year',
                                           'incident_day_of_week','report_datetime', 'row_id',
                                           'incident_id', 'incident_number', 'cad_number', 'report_type_code',
                                           'report_type_description', 'incident_code', 'incident_category',
                                           'incident_subcategory', 'incident_description', 'resolution',
                                           'intersection', 'cnn', 'police_district', 'analysis_neighborhood',
                                           'supervisor_district', 'latitude', 'longitude'
                                          ]]
df_results_20182020

,Date,hourOfDay,minuteOfDay,incident_year,incident_day_of_week,report_datetime,row_id,incident_id,incident_number,cad_number,...,incident_subcategory,incident_description,resolution,intersection,cnn,police_district,analysis_neighborhood,supervisor_district,latitude,longitude
0,2018-01-01,0,0,2018,Monday,2019-03-18T14:42:00.000,78096309029,780963,190194260,190772349,...,Fraud,False Personation to Receive Money or Property,Open or Active,ELGIN PARK \ MCCOPPIN ST,25848000,Richmond,Mission,8,37.77147797080469,-122.42333489741378
1,2018-01-01,0,0,2018,Monday,2020-02-16T18:25:00.000,90346371013,903463,200118738,200472725,...,Theft From Vehicle,"License Plate, Stolen",Open or Active,19TH ST \ FLORIDA ST,24030000,Mission,Mission,9,37.760427451635174,-122.41096197259283
2,2018-01-01,0,0,2018,Monday,2018-03-12T08:44:00.000,64491209029,644912,180187667,180710832,...,Fraud,False Personation to Receive Money or Property,Open or Active,VARA ST \ MISSION BAY BLVD,34184000,Southern,Mission Bay,6,37.77121525905079,-122.38777795668946
3,2018-01-01,0,0,2018,Monday,2019-04-11T00:00:00.000,89256975030,892569,190257313,191011914,...,Case Closure,Case Closure,Unfounded,19TH AVE \ SAINT CHARLES AVE,33462000,Bayview,Oceanview/Merced/Ingleside,11,37.71381201539547,-122.46932230799413
4,2018-01-01,0,0,2018,Monday,2019-04-11T00:00:00.000,89256909060,892569,190257313,191011914,...,Fraud,Real Estate Fraud,Unfounded,19TH AVE \ SAINT CHARLES AVE,33462000,Bayview,Oceanview/Merced/Ingleside,11,37.71381201539547,-122.46932230799413
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417109,2020-12-31,23,30,2020,Thursday,2021-01-11T14:48:00.000,99504806232,995048,210023622,210111991,...,Larceny - Auto Parts,"Theft, Vehicle Strip, $50-$200",Open or Active,04TH ST \ LONG BRIDGE ST,34168000,Southern,Mission Bay,6,37.773466920607476,-122.39143433652146
417110,2020-12-31,23,30,2020,Thursday,2021-01-04T16:52:00.000,99296805042,992968,210007654,210042387,...,Burglary - Residential,"Burglary, Residence, Att. Forcible Entry",Open or Active,18TH AVE \ KIRKHAM ST,27363000,Taraval,Inner Sunset,7,37.759879432848436,-122.47579656403286
417111,2020-12-31,23,34,2020,Thursday,2020-12-31T23:39:00.000,99193064020,991930,200791221,203663458,...,Other,Mental Health Detention,Open or Active,WELSH ST \ 05TH ST,23888000,Southern,South of Market,6,37.77737199450485,-122.39976258647586
417112,2020-12-31,23,39,2020,Thursday,2020-12-31T23:40:00.000,99191465015,991914,200791237,203663275,...,Other,"Driving, No License Issued",Cite or Arrest Adult,AL SCOMA WAY \ JEFFERSON ST,35066000,Central,North Beach,3,37.807978726080414,-122.417715898404
417113,2020-12-31,23,55,2020,Thursday,2021-01-01T00:24:00.000,99191304134,991913,210000034,210010091,...,Simple Assault,Battery,Cite or Arrest Adult,GEARY ST \ SHANNON ST,24962000,Central,Tenderloin,6,37.7868345113598,-122.41234030428764

In [34]:
#storing 
df_results_20182020.to_pickle("../data/df_clean_results_20182020_raw.pkl")

In [62]:
# ensure that the Date is in the right format
df_results_20182020['Date'] = pd.to_datetime(df_results_20182020['incident_date']) 
df_results_20182020.head()

,incident_datetime,incident_date,incident_time,incident_year,incident_day_of_week,report_datetime,row_id,incident_id,incident_number,cad_number,...,:@computed_region_26cr_cadq,:@computed_region_ajp5_b2md,:@computed_region_6pnf_4xz7,:@computed_region_h4ep_8xdi,:@computed_region_nqbw_i6c3,filed_online,:@computed_region_2dwj_jsy4,:@computed_region_jg9y_a9du,:@computed_region_y6ts_4iup,Date
0,2018-01-01T09:26:00.000,2018-01-01T00:00:00.000,09:26,2018,Monday,2018-01-01T09:27:00.000,61893007041,618930,171052174,173641140,...,9,1,2,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-01
1,2018-01-01T02:30:00.000,2018-01-01T00:00:00.000,02:30,2018,Monday,2018-01-01T08:21:00.000,61893105041,618931,180000768,180010668,...,1,7,2,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-01
2,2018-01-01T10:00:00.000,2018-01-01T00:00:00.000,10:00,2018,Monday,2018-01-01T10:20:00.000,61893275000,618932,180000605,180010893,...,10,36,2,1,NaN,NaN,NaN,NaN,NaN,2018-01-01
3,2018-01-01T10:03:00.000,2018-01-01T00:00:00.000,10:03,2018,Monday,2018-01-01T10:04:00.000,61893565015,618935,180000887,180011579,...,1,28,1,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-01
4,2018-01-01T09:01:00.000,2018-01-01T00:00:00.000,09:01,2018,Monday,2018-01-01T09:39:00.000,61893607041,618936,171052958,180011403,...,3,6,2,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-01

In [63]:
# Make a boolean mask. start_date and end_date can be 
# datetime.datetimes, np.datetime64s, pd.Timestamps, or even datetime strings
start_date = "01/01/2018"
end_date = "01/01/2021"
mask = (df_results_20182020['Date'] >= start_date) & (df_results_20182020['Date'] < end_date)

df_results_20182020 = df_results_20182020.loc[mask].sort_values(by=['Date'], inplace=False, ascending=True)

In [65]:
df_results_20182020

,incident_datetime,incident_date,incident_time,incident_year,incident_day_of_week,report_datetime,row_id,incident_id,incident_number,cad_number,...,:@computed_region_26cr_cadq,:@computed_region_ajp5_b2md,:@computed_region_6pnf_4xz7,:@computed_region_h4ep_8xdi,:@computed_region_nqbw_i6c3,filed_online,:@computed_region_2dwj_jsy4,:@computed_region_jg9y_a9du,:@computed_region_y6ts_4iup,Date
0,2018-01-01T09:26:00.000,2018-01-01T00:00:00.000,09:26,2018,Monday,2018-01-01T09:27:00.000,61893007041,618930,171052174,173641140,...,9,1,2,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-01
7174,2018-01-01T19:45:00.000,2018-01-01T00:00:00.000,19:45,2018,Monday,2018-01-01T19:45:00.000,61905616710,619056,180002322,180013579,...,9,40,2,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-01
7175,2018-01-01T19:45:00.000,2018-01-01T00:00:00.000,19:45,2018,Monday,2018-01-01T19:45:00.000,61905663010,619056,180002322,180013579,...,9,40,2,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-01
7176,2018-01-01T19:09:00.000,2018-01-01T00:00:00.000,19:09,2018,Monday,2018-01-01T19:10:00.000,61905704083,619057,180002253,180013459,...,9,1,2,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-01
7177,2018-01-01T19:09:00.000,2018-01-01T00:00:00.000,19:09,2018,Monday,2018-01-01T19:10:00.000,61905712080,619057,180002253,180013459,...,9,1,2,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414918,2020-12-31T18:30:00.000,2020-12-31T00:00:00.000,18:30,2020,Thursday,2020-12-31T19:04:00.000,99196628150,991966,206178148,NaN,...,11,3,1,NaN,NaN,True,NaN,NaN,NaN,2020-12-31
414917,2020-12-31T22:05:00.000,2020-12-31T00:00:00.000,22:05,2020,Thursday,2020-12-31T22:13:00.000,99188819057,991888,200791099,203663195,...,10,36,2,1,NaN,NaN,NaN,NaN,NaN,2020-12-31
422759,2020-12-31T00:00:00.000,2020-12-31T00:00:00.000,00:00,2020,Thursday,2021-01-19T09:36:00.000,99804306244,998043,216006959,NaN,...,6,32,1,NaN,NaN,True,NaN,NaN,NaN,2020-12-31
414909,2020-12-31T15:00:00.000,2020-12-31T00:00:00.000,15:00,2020,Thursday,2021-01-01T13:53:00.000,99205604170,992056,210001145,210011707,...,10,36,2,1,NaN,NaN,NaN,NaN,NaN,2020-12-31
414482,2020-12-31T15:42:00.000,2020-12-31T00:00:00.000,15:42,2020,Thursday,2020-12-31T15:46:00.000,99182068050,991820,200790364,203661981,...,2,20,2,NaN,3,NaN,NaN,NaN,NaN,2020-12-31

In [73]:
df_results_20182020.columns

Index(['Date', 'incident_datetime', 'incident_date', 'incident_time',
       'incident_year', 'incident_day_of_week', 'report_datetime', 'row_id',
       'incident_id', 'incident_number', 'cad_number', 'report_type_code',
       'report_type_description', 'incident_code', 'incident_category',
       'incident_subcategory', 'incident_description', 'resolution',
       'intersection', 'cnn', 'police_district', 'analysis_neighborhood',
       'supervisor_district', 'latitude', 'longitude', 'point',
       ':@computed_region_6qbp_sg9q', ':@computed_region_qgnn_b9vv',
       ':@computed_region_26cr_cadq', ':@computed_region_ajp5_b2md',
       ':@computed_region_6pnf_4xz7', ':@computed_region_h4ep_8xdi',
       ':@computed_region_nqbw_i6c3', 'filed_online',
       ':@computed_region_2dwj_jsy4', ':@computed_region_jg9y_a9du',
       ':@computed_region_y6ts_4iup'],
      dtype='object')

In [80]:
print (*list(df_results_20132018.columns), sep = "\n")

pdid
incidntnum
incident_code
category
descript
dayofweek
date
time
pddistrict
resolution
address
x
y

In [ ]:
df_results_20182020 = resetColumns(df_results_20182020,frompos = -1,insertAt=0)
df_results_20182020 = df_results_20182020[['incident_date','incident_time','incident_year','incident_day_of_week','report_datetime', 'row_id',
       'incident_id', 'incident_number', 'cad_number', 'report_type_code',
       'report_type_description', 'incident_code', 'incident_category',
       'incident_subcategory', 'incident_description', 'resolution',
       'intersection', 'cnn', 'police_district', 'analysis_neighborhood',
       'supervisor_district', 'latitude', 'longitude']]

df_results_20182020 = df_results_20182020.rename(columns={'oldName1': 'newName1', 
                                                          'oldName2': 'newName2'}


                                                )

In [75]:
df_results_20182020 = resetColumns(df_results_20182020,frompos = -1,insertAt=0)
df_results_20182020 = df_results_20182020[['Date','incident_time','incident_year','incident_day_of_week','report_datetime', 'row_id',
       'incident_id', 'incident_number', 'cad_number', 'report_type_code',
       'report_type_description', 'incident_code', 'incident_category',
       'incident_subcategory', 'incident_description', 'resolution',
       'intersection', 'cnn', 'police_district', 'analysis_neighborhood',
       'supervisor_district', 'latitude', 'longitude']]
df_results_20182020

,Date,incident_time,incident_year,incident_day_of_week,report_datetime,row_id,incident_id,incident_number,cad_number,report_type_code,...,incident_subcategory,incident_description,resolution,intersection,cnn,police_district,analysis_neighborhood,supervisor_district,latitude,longitude
0,2018-01-01,09:26,2018,Monday,2018-01-01T09:27:00.000,61893007041,618930,171052174,173641140,VS,...,Recovered Vehicle,"Vehicle, Recovered, Auto",Open or Active,03RD ST \ HOLLISTER AVE,20471000,Southern,Bayview Hunters Point,10,37.72171587946975,-122.39594382884452
7174,2018-01-01,19:45,2018,Monday,2018-01-01T19:45:00.000,61905616710,619056,180002322,180013579,II,...,Drug Violation,"Narcotics Paraphernalia, Possession of",Cite or Arrest Adult,BLYTHDALE AVE \ SANTOS ST,20423000,Ingleside,Visitacion Valley,10,37.71073194458116,-122.41877184294184
7175,2018-01-01,19:45,2018,Monday,2018-01-01T19:45:00.000,61905663010,619056,180002322,180013579,II,...,Other,"Warrant Arrest, Local SF Warrant",Cite or Arrest Adult,BLYTHDALE AVE \ SANTOS ST,20423000,Ingleside,Visitacion Valley,10,37.71073194458116,-122.41877184294184
7176,2018-01-01,19:09,2018,Monday,2018-01-01T19:10:00.000,61905704083,619057,180002253,180013459,II,...,Aggravated Assault,"Firearm, Discharging in Grossly Negligent Manner",Cite or Arrest Adult,WESTBROOK CT \ HUDSON AVE,20189000,Bayview,Bayview Hunters Point,10,37.73497690238017,-122.38313398537929
7177,2018-01-01,19:09,2018,Monday,2018-01-01T19:10:00.000,61905712080,619057,180002253,180013459,II,...,Weapons Offense,"Firearm, Possession By Prohibited Person",Cite or Arrest Adult,WESTBROOK CT \ HUDSON AVE,20189000,Bayview,Bayview Hunters Point,10,37.73497690238017,-122.38313398537929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414918,2020-12-31,18:30,2020,Thursday,2020-12-31T19:04:00.000,99196628150,991966,206178148,NaN,II,...,Vandalism,"Malicious Mischief, Vandalism to Property",Open or Active,HAIGHT ST \ COLE ST,26414000,Park,Haight Ashbury,5,37.769526043647296,-122.45071018189665
414917,2020-12-31,22:05,2020,Thursday,2020-12-31T22:13:00.000,99188819057,991888,200791099,203663195,II,...,Intimidation,Terrorist Threats,Cite or Arrest Adult,EDDY ST \ LEAVENWORTH ST,24935000,Tenderloin,Tenderloin,6,37.78372378203807,-122.41424157409635
422759,2020-12-31,00:00,2020,Thursday,2021-01-19T09:36:00.000,99804306244,998043,216006959,NaN,II,...,Larceny - From Vehicle,"Theft, From Locked Vehicle, >$950",Open or Active,VAN NESS AVE \ BROADWAY,26547000,Northern,Russian Hill,2,37.79573710834212,-122.42341305643612
414909,2020-12-31,15:00,2020,Thursday,2021-01-01T13:53:00.000,99205604170,992056,210001145,210011707,II,...,Simple Assault,False Imprisonment,Open or Active,ELLIS ST \ HYDE ST,25144000,Tenderloin,Tenderloin,6,37.784448840613585,-122.41607173623363
414482,2020-12-31,15:42,2020,Thursday,2020-12-31T15:46:00.000,99182068050,991820,200790364,203661981,II,...,Traffic Collision,Traffic Collision,Cite or Arrest Adult,SOUTH VAN NESS AVE \ CESAR CHAVEZ ST,33364000,Mission,Mission,9,37.748212149468735,-122.41586279405455

In [76]:
#storing 
df_results_20182020.to_pickle("../data/df_results_20182020_raw.pkl")

In [22]:
results_df.columns

Index(['incident_datetime', 'incident_date', 'incident_time', 'incident_year',
       'incident_day_of_week', 'report_datetime', 'row_id', 'incident_id',
       'incident_number', 'cad_number', 'report_type_code',
       'report_type_description', 'incident_code', 'incident_category',
       'incident_subcategory', 'incident_description', 'resolution',
       'intersection', 'cnn', 'police_district', 'analysis_neighborhood',
       'supervisor_district', 'latitude', 'longitude', 'point',
       ':@computed_region_6qbp_sg9q', ':@computed_region_qgnn_b9vv',
       ':@computed_region_26cr_cadq', ':@computed_region_ajp5_b2md',
       ':@computed_region_6pnf_4xz7', ':@computed_region_h4ep_8xdi',
       ':@computed_region_nqbw_i6c3', 'filed_online',
       ':@computed_region_2dwj_jsy4', ':@computed_region_jg9y_a9du',
       ':@computed_region_y6ts_4iup'],
      dtype='object')

In [24]:
results_df.incident_category.unique()

array(['Recovered Vehicle', 'Burglary', 'Missing Person',
       'Other Miscellaneous', 'Assault', 'Non-Criminal', 'Larceny Theft',
       'Suspicious Occ', 'Robbery', 'Weapons Carrying Etc',
       'Civil Sidewalks', 'Fraud', 'Malicious Mischief', 'Warrant',
       'Traffic Violation Arrest', 'Miscellaneous Investigation',
       'Stolen Property', 'Drug Offense', 'Weapons Offense',
       'Motor Vehicle Theft', 'Traffic Collision', 'Disorderly Conduct',
       'Vehicle Misplaced', 'Offences Against The Family And Children',
       'Forgery And Counterfeiting', 'Lost Property', 'Drug Violation',
       'Other', 'Other Offenses', 'Arson', 'Vehicle Impounded',
       'Fire Report', 'Case Closure', 'Embezzlement', 'Suicide',
       'Courtesy Report', 'Vandalism', 'Gambling', 'Sex Offense',
       'Prostitution', 'Human Trafficking (A), Commercial Sex Acts',
       'Liquor Laws', 'Suspicious', 'Motor Vehicle Theft?', nan,
       'Homicide', 'Rape'], dtype=object)

In [23]:
results_df.incident_description[42]

'Theft, Other Property, $50-$200'

# Loading

In [7]:
#loading 
df = pd.read_pickle("../data/df_SFlistings.pkl")

In [8]:
with open("../data/sfpd.geojson") as f:
    geojson = json.load(f)

In [ ]:
def refreshSanFrancisco():
    bandwMap = folium.Map([37.7749, -122.4194],
               tiles="Stamen Toner",
               API_key=mytoken,zoom_start=13)

    return bandwMap

In [ ]:
m = refreshSanFrancisco()

In [ ]:
t2t = {0: 0,
       100: 1,
            "Wednesday":2,
            'Thursday':3, 
            'Friday':4, 
            'Saturday':5, 
            'Sunday':6
            }

# edit sf_weather_data

In [23]:
sf_weather_data = pd.read_csv("../data/sf-20082021/weather_data_1hr.csv")
#sf_weather_data['time'] = sf_weather_data['time'].apply(str)

In [24]:
sf_weather_data["hourOfDay"]= (sf_weather_data["time"]/100).apply(int)
sf_weather_data = resetColumns(sf_weather_data,frompos = -1,insertAt=1)

In [25]:
sf_weather_data.columns

Index(['loc_id', 'hourOfDay', 'date', 'time', 'isdaytime', 'tempC', 'tempF',
       'windspeedMiles', 'windspeedKmph', 'winddirdegree', 'winddir16point',
       'weatherCode', 'weatherIconUrl', 'weatherDesc', 'precipMM',
       'precipInches', 'humidity', 'visibilityKm', 'visibilityMiles',
       'pressureMB', 'pressureInches', 'cloudcover', 'HeatIndexC',
       'HeatIndexF', 'DewPointC', 'DewPointF', 'WindChillC', 'WindChillF',
       'WindGustMiles', 'WindGustKmph', 'FeelsLikeC', 'FeelsLikeF', 'uvIndex'],
      dtype='object')

In [26]:
w = sf_weather_data[['date', 'hourOfDay', 'isdaytime', 
                     'tempC','humidity','pressureMB','precipMM',
                     'cloudcover', 'HeatIndexC','uvIndex',
                     'windspeedKmph','winddirdegree',
                     'weatherCode','weatherDesc'
                    ]]
w

,date,hourOfDay,isdaytime,tempC,humidity,pressureMB,precipMM,cloudcover,HeatIndexC,uvIndex,windspeedKmph,winddirdegree,weatherCode,weatherDesc
0,2008-07-01,0,no,12,94,1016,0.0,47,12,1,6,267,116,Partly cloudy
1,2008-07-01,1,no,12,94,1016,0.0,45,12,1,7,266,116,Partly cloudy
2,2008-07-01,2,no,12,95,1016,0.1,43,12,1,8,265,143,Mist
3,2008-07-01,3,no,12,95,1016,0.0,41,12,1,9,264,143,Mist
4,2008-07-01,4,no,12,91,1016,0.0,48,12,1,8,262,143,Mist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111787,2021-04-01,19,yes,19,44,1013,0.0,0,19,5,11,268,113,Sunny
111788,2021-04-01,20,no,18,47,1013,0.0,0,18,1,9,265,113,Clear
111789,2021-04-01,21,no,17,50,1013,0.0,0,17,1,8,263,113,Clear
111790,2021-04-01,22,no,17,52,1014,0.0,0,17,1,7,259,113,Clear
111791,2021-04-01,23,no,17,55,1014,0.0,0,17,1,6,255,113,Clear

In [27]:
w = addDate(w,"date")
w

/Users/ariannataormina/Documents/GitHub/DataAnalysisExample/code/functions_df.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df[columnWithDate])

,Date,date,hourOfDay,isdaytime,tempC,humidity,pressureMB,precipMM,cloudcover,HeatIndexC,uvIndex,windspeedKmph,winddirdegree,weatherCode,weatherDesc
0,2008-07-01,2008-07-01,0,no,12,94,1016,0.0,47,12,1,6,267,116,Partly cloudy
1,2008-07-01,2008-07-01,1,no,12,94,1016,0.0,45,12,1,7,266,116,Partly cloudy
2,2008-07-01,2008-07-01,2,no,12,95,1016,0.1,43,12,1,8,265,143,Mist
3,2008-07-01,2008-07-01,3,no,12,95,1016,0.0,41,12,1,9,264,143,Mist
4,2008-07-01,2008-07-01,4,no,12,91,1016,0.0,48,12,1,8,262,143,Mist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111787,2021-04-01,2021-04-01,19,yes,19,44,1013,0.0,0,19,5,11,268,113,Sunny
111788,2021-04-01,2021-04-01,20,no,18,47,1013,0.0,0,18,1,9,265,113,Clear
111789,2021-04-01,2021-04-01,21,no,17,50,1013,0.0,0,17,1,8,263,113,Clear
111790,2021-04-01,2021-04-01,22,no,17,52,1014,0.0,0,17,1,7,259,113,Clear
111791,2021-04-01,2021-04-01,23,no,17,55,1014,0.0,0,17,1,6,255,113,Clear

In [28]:
def formatWData(df,insertAt=1, hourshift = 0):
    df['NumDayOfWeek'] = df['Date'].dt.dayofweek
    #df['Date'] = df['Date'].dt.date
    df = resetColumns(df,frompos = -1,insertAt=1)
    return df

In [29]:
wfor = formatWData(w)

<ipython-input-28-a4123b091707>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NumDayOfWeek'] = df['Date'].dt.dayofweek

In [30]:
wfor

,Date,NumDayOfWeek,date,hourOfDay,isdaytime,tempC,humidity,pressureMB,precipMM,cloudcover,HeatIndexC,uvIndex,windspeedKmph,winddirdegree,weatherCode,weatherDesc
0,2008-07-01,1,2008-07-01,0,no,12,94,1016,0.0,47,12,1,6,267,116,Partly cloudy
1,2008-07-01,1,2008-07-01,1,no,12,94,1016,0.0,45,12,1,7,266,116,Partly cloudy
2,2008-07-01,1,2008-07-01,2,no,12,95,1016,0.1,43,12,1,8,265,143,Mist
3,2008-07-01,1,2008-07-01,3,no,12,95,1016,0.0,41,12,1,9,264,143,Mist
4,2008-07-01,1,2008-07-01,4,no,12,91,1016,0.0,48,12,1,8,262,143,Mist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111787,2021-04-01,3,2021-04-01,19,yes,19,44,1013,0.0,0,19,5,11,268,113,Sunny
111788,2021-04-01,3,2021-04-01,20,no,18,47,1013,0.0,0,18,1,9,265,113,Clear
111789,2021-04-01,3,2021-04-01,21,no,17,50,1013,0.0,0,17,1,8,263,113,Clear
111790,2021-04-01,3,2021-04-01,22,no,17,52,1014,0.0,0,17,1,7,259,113,Clear
111791,2021-04-01,3,2021-04-01,23,no,17,55,1014,0.0,0,17,1,6,255,113,Clear

In [36]:
start_date = "01/07/2008" # mm/dd/yyyy
end_date = "01/01/2021"
mask = (wfor['Date'] >= start_date) & (wfor['Date'] < end_date)
wformasked = wfor.loc[mask].sort_values(by=['date',"hourOfDay"], inplace=False, ascending=True)

In [37]:
wformasked

,Date,NumDayOfWeek,date,hourOfDay,isdaytime,tempC,humidity,pressureMB,precipMM,cloudcover,HeatIndexC,uvIndex,windspeedKmph,winddirdegree,weatherCode,weatherDesc
0,2008-07-01,1,2008-07-01,0,no,12,94,1016,0.0,47,12,1,6,267,116,Partly cloudy
1,2008-07-01,1,2008-07-01,1,no,12,94,1016,0.0,45,12,1,7,266,116,Partly cloudy
2,2008-07-01,1,2008-07-01,2,no,12,95,1016,0.1,43,12,1,8,265,143,Mist
3,2008-07-01,1,2008-07-01,3,no,12,95,1016,0.0,41,12,1,9,264,143,Mist
4,2008-07-01,1,2008-07-01,4,no,12,91,1016,0.0,48,12,1,8,262,143,Mist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109603,2020-12-31,3,2020-12-31,19,yes,13,74,1019,0.0,3,13,4,8,298,116,Partly cloudy
109604,2020-12-31,3,2020-12-31,20,no,12,77,1019,0.0,3,12,1,7,308,116,Partly cloudy
109605,2020-12-31,3,2020-12-31,21,no,12,79,1019,0.0,4,12,1,6,317,116,Partly cloudy
109606,2020-12-31,3,2020-12-31,22,no,12,78,1019,0.0,7,12,1,6,290,116,Partly cloudy
109607,2020-12-31,3,2020-12-31,23,no,11,78,1020,0.0,11,11,1,6,263,116,Partly cloudy

In [38]:
wformasked = wformasked[['Date', 'NumDayOfWeek', 'hourOfDay', 'isdaytime', 'tempC',
       'humidity', 'pressureMB', 'precipMM', 'cloudcover', 'HeatIndexC',
       'uvIndex', 'windspeedKmph', 'winddirdegree', 'weatherDesc']]

In [39]:
wformasked.reset_index(inplace=True,drop=True)

In [40]:
wformasked

,Date,NumDayOfWeek,hourOfDay,isdaytime,tempC,humidity,pressureMB,precipMM,cloudcover,HeatIndexC,uvIndex,windspeedKmph,winddirdegree,weatherDesc
0,2008-07-01,1,0,no,12,94,1016,0.0,47,12,1,6,267,Partly cloudy
1,2008-07-01,1,1,no,12,94,1016,0.0,45,12,1,7,266,Partly cloudy
2,2008-07-01,1,2,no,12,95,1016,0.1,43,12,1,8,265,Mist
3,2008-07-01,1,3,no,12,95,1016,0.0,41,12,1,9,264,Mist
4,2008-07-01,1,4,no,12,91,1016,0.0,48,12,1,8,262,Mist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109603,2020-12-31,3,19,yes,13,74,1019,0.0,3,13,4,8,298,Partly cloudy
109604,2020-12-31,3,20,no,12,77,1019,0.0,3,12,1,7,308,Partly cloudy
109605,2020-12-31,3,21,no,12,79,1019,0.0,4,12,1,6,317,Partly cloudy
109606,2020-12-31,3,22,no,12,78,1019,0.0,7,12,1,6,290,Partly cloudy
109607,2020-12-31,3,23,no,11,78,1020,0.0,11,11,1,6,263,Partly cloudy

In [41]:
wformasked.to_pickle("../data/sf_weather_clean_20082020_raw.pkl")